Repository woodpecker-ci/autoscaler, pull requests merged in 2025-01, with the labels that each got.

#250 Fix deprecated editorconfig filename
  .editorconfig-checker.json
Labels: build

#227 Wait for AWS instance availablity before returning
  engine/autoscaler.go
  providers/aws/provider.go
Labels: enhancement

#251 Add Vultr provider
  README.md
  cmd/woodpecker-autoscaler/main.go
  go.mod
  go.sum
  providers/aws/provider.go
  providers/linode/provider.go
  providers/vultr/flags.go
  providers/vultr/provider.go
  server/client.go
Labels: feature

#252 Add Scaleway provider
  README.md
  cmd/woodpecker-autoscaler/main.go
  go.mod
  go.sum
  providers/aws/flags.go
  providers/linode/provider.go
  providers/scaleway/flags.go
  providers/scaleway/provider.go
  providers/vultr/flags.go
Labels: feature

#259 docs: fix typos
  README.md
Labels: documentation
